DROP DATABASE IF EXISTS gestao_receitas;
CREATE DATABASE gestao_receitas;
USE gestao_receitas;

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE favorite_recipes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    recipe_id INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE recipes_collection (
    id INT PRIMARY KEY AUTO_INCREMENT,
    collection_id VARCHAR(255) NOT NULL,
    recipe_id INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO users (
    name,
    email,
    password,
    role
) VALUES (
    'Admin',
    'admin@gestao.receitas',
    '$2a$10$tFdDiY885VtLkFFR.U0T9O2.HragJ3eRenDP4wlHiHtv2wO7r4LGe',
    1
);

 -- 1: Admin, 2: User
 -- Password: Admin123
